export const MOCK_USER_STUDENT = {
    id: "stu001",
    name: "Rahul Sharma",
    email: "student@bca.edu",
    role: "student",
    usn: "1BCA21CS001",
    semester: 4,
    is_active: true,
    created_at: "2026-02-18T08:00:00Z",
};

export const MOCK_USER_FACULTY = {
    id: "fac001",
    name: "Prof. Sharma",
    email: "faculty@bca.edu",
    role: "faculty",
    subject_ids: ["sub001", "sub002"],
    is_active: true,
    created_at: "2026-01-10T08:00:00Z",
};

export const MOCK_USER_HOD = {
    id: "hod001",
    name: "Dr. Mehta",
    email: "hod@bca.edu",
    role: "hod",
    is_active: true,
    created_at: "2025-06-01T08:00:00Z",
};

export const MOCK_SUBJECTS = [
    {
        id: "sub001",
        code: "BCA401",
        name: "Data Structures",
        semester: 4,
        faculty_id: "fac001",
        faculty_name: "Prof. Sharma",
    },
    {
        id: "sub002",
        code: "BCA402",
        name: "Operating Systems",
        semester: 4,
        faculty_id: "fac001",
        faculty_name: "Prof. Sharma",
    },
    {
        id: "sub003",
        code: "BCA301",
        name: "DBMS",
        semester: 3,
        faculty_id: "fac002",
        faculty_name: "Prof. Verma",
    },
    {
        id: "sub004",
        code: "BCA201",
        name: "Programming in C",
        semester: 2,
        faculty_id: "fac003",
        faculty_name: "Prof. Rao",
    },
];

export const MOCK_RESOURCES = [
    {
        id: "res001",
        title: "Unit 3 - Trees & Graphs",
        description: "Comprehensive notes on tree traversal and graph algorithms",
        resource_type: "file",
        file_format: "pdf",
        original_filename: "trees_graphs.pdf",
        file_url: "http://localhost:8000/media/uploads/4/BCA401/trees_graphs.pdf",
        semester: 4,
        subject_id: "sub001",
        subject_code: "BCA401",
        subject_name: "Data Structures",
        unit: "Unit 3",
        tags: ["trees", "graphs", "BFS", "DFS"],
        uploaded_by: "fac001",
        uploader_name: "Prof. Sharma",
        uploader_role: "faculty",
        status: "approved",
        download_count: 134,
        upload_date: "2026-02-18T10:00:00Z",
    },
    {
        id: "res002",
        title: "OS Process Scheduling Notes",
        description: "FCFS, SJF, Round Robin explained with examples",
        resource_type: "file",
        file_format: "ppt",
        original_filename: "process_scheduling.pptx",
        file_url: "http://localhost:8000/media/uploads/4/BCA402/process_scheduling.pptx",
        semester: 4,
        subject_id: "sub002",
        subject_code: "BCA402",
        subject_name: "Operating Systems",
        unit: "Unit 2",
        tags: ["scheduling", "FCFS", "round robin"],
        uploaded_by: "fac001",
        uploader_name: "Prof. Sharma",
        uploader_role: "faculty",
        status: "approved",
        download_count: 89,
        upload_date: "2026-02-17T14:00:00Z",
    },
    {
        id: "res003",
        title: "GeeksForGeeks - Tree Traversal Reference",
        description: "Useful external reference for tree algorithms",
        resource_type: "url",
        url: "https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/",
        semester: 4,
        subject_id: "sub001",
        subject_code: "BCA401",
        subject_name: "Data Structures",
        unit: "Unit 3",
        tags: ["trees", "reference", "geeksforgeeks"],
        uploaded_by: "fac001",
        uploader_name: "Prof. Sharma",
        uploader_role: "faculty",
        status: "approved",
        download_count: 0,
        upload_date: "2026-02-16T09:00:00Z",
    },
    {
        id: "res004",
        title: "My Handwritten DS Notes - Unit 1",
        description: "Notes from class on arrays and linked lists",
        resource_type: "file",
        file_format: "image",
        original_filename: "ds_notes_unit1.jpg",
        file_url: "http://localhost:8000/media/uploads/4/BCA401/ds_notes_unit1.jpg",
        semester: 4,
        subject_id: "sub001",
        subject_code: "BCA401",
        subject_name: "Data Structures",
        unit: "Unit 1",
        tags: ["arrays", "linked lists", "handwritten"],
        uploaded_by: "stu001",
        uploader_name: "Rahul Sharma",
        uploader_role: "student",
        status: "approved",
        download_count: 22,
        upload_date: "2026-02-15T11:00:00Z",
    },
];

export const MOCK_PENDING_RESOURCES = [
    {
        id: "res005",
        title: "Stack and Queue Summary",
        description: "",
        resource_type: "file",
        file_format: "doc",
        original_filename: "stack_queue.docx",
        file_url: "http://localhost:8000/media/uploads/4/BCA401/stack_queue.docx",
        semester: 4,
        subject_id: "sub001",
        subject_code: "BCA401",
        subject_name: "Data Structures",
        unit: "Unit 2",
        tags: ["stack", "queue"],
        uploaded_by: "stu001",
        uploader_name: "Rahul Sharma",
        uploader_role: "student",
        status: "pending",
        download_count: 0,
        upload_date: "2026-02-20T09:30:00Z",
    },
];

export const MOCK_NOTICES = [
    {
        id: "not001",
        title: "Mid-Term Exam Schedule Released",
        body: "Mid-term exams are scheduled from March 10–14. Detailed timetable is posted on the department board.",
        posted_by: "hod001",
        posted_by_name: "Dr. Mehta",
        is_pinned: true,
        is_new: false,
        created_at: "2026-02-15T08:00:00Z",
        expires_at: null,
    },
    {
        id: "not002",
        title: "Assignment 2 Deadline Extended",
        body: "The deadline for BCA401 Assignment 2 has been extended to February 28th due to the lab maintenance.",
        posted_by: "fac001",
        posted_by_name: "Prof. Sharma",
        is_pinned: false,
        is_new: true,
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        expires_at: "2026-02-28T00:00:00Z",
    },
    {
        id: "not003",
        title: "Corpus is Now Live",
        body: "The department's centralized resource portal is now operational. Upload your notes and access study materials here.",
        posted_by: "hod001",
        posted_by_name: "Dr. Mehta",
        is_pinned: false,
        is_new: false,
        created_at: "2026-02-10T10:00:00Z",
        expires_at: null,
    },
];

export const MOCK_ANALYTICS = {
    summary: {
        total_users: 87,
        total_students: 80,
        total_faculty: 6,
        total_resources: 142,
        pending_approvals: 5,
        total_notices: 12,
        total_downloads: 1834,
    },
    uploadsBySemester: [
        { semester: 1, count: 12 },
        { semester: 2, count: 18 },
        { semester: 3, count: 24 },
        { semester: 4, count: 41 },
        { semester: 5, count: 30 },
        { semester: 6, count: 17 },
    ],
    topResources: [
        {
            id: "res001",
            title: "Unit 3 - Trees & Graphs",
            subject_code: "BCA401",
            download_count: 134,
        },
        {
            id: "res002",
            title: "OS Process Scheduling",
            subject_code: "BCA402",
            download_count: 89,
        },
        {
            id: "res004",
            title: "My Handwritten DS Notes",
            subject_code: "BCA401",
            download_count: 22,
        },
    ],
    facultyActivity: [
        {
            faculty_id: "fac001",
            faculty_name: "Prof. Sharma",
            uploads: 18,
            approvals: 12,
            rejections: 3,
        },
        {
            faculty_id: "fac002",
            faculty_name: "Prof. Verma",
            uploads: 11,
            approvals: 8,
            rejections: 1,
        },
    ],
    uploadsByFormat: [
        { format: "pdf", count: 78 },
        { format: "ppt", count: 31 },
        { format: "doc", count: 14 },
        { format: "image", count: 19 },
    ],
};

export const MOCK_SEARCH_RESULTS = (query) => ({
    query,
    count: 2,
    results: MOCK_RESOURCES.filter(
        (r) =>
            r.title.toLowerCase().includes(query.toLowerCase()) ||
            r.tags.some((t) => t.toLowerCase().includes(query.toLowerCase())),
    ).map((r) => ({ ...r, similarity_score: 0.92 })),
});

export const MOCK_FACULTY_USERS = [
    {
        id: "fac001",
        name: "Prof. Sharma",
        email: "faculty@bca.edu",
        role: "faculty",
        is_active: true,
    },
    {
        id: "fac002",
        name: "Prof. Verma",
        email: "verma@bca.edu",
        role: "faculty",
        is_active: true,
    },
    {
        id: "fac003",
        name: "Prof. Rao",
        email: "rao@bca.edu",
        role: "faculty",
        is_active: false,
    },
];
